name: .NET Core 6 Desktop

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Com2vPilotVolumeSolution.sln               # Replace with your solution name, i.e. MyWpfApp.sln.
      Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies I
      run: dotnet restore WinCoreAudioApiLib/WinCoreAudioApiLib.csproj

    - name: Restore dependencies II
      run: dotnet restore Com2vPilotVolume/Com2vPilotVolume.csproj

    - name: Build app
      run: dotnet publish Com2vPilotVolume/Com2vPilotVolume.csproj -c Release -o output

    - name: Copy README.md to output
      run: copy README.md output\README.md

    - name: Copy License to output
      run: copy LICENSE output\LICENSE      

    - name: Zip build output
      run: powershell Compress-Archive -Path output\* -DestinationPath build.zip

    - name: Upload to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        destination_dir: preview-build
        keep_files: true

